- name: Run Nginx container via Ansible
  hosts: localhost
  connection: local
  become: yes

  tasks:
    - name: Run nginx container
      community.docker.docker_container:
        name: nginx-ansible
        image: nginx
        state: started
        ports:
          - "8090:80"
